//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace osucatch_editor_realtimeviewer {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.13.0.0")]
    internal sealed partial class app : global::System.Configuration.ApplicationSettingsBase {
        
        private static app defaultInstance = ((app)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new app())));
        
        public static app Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int Window_Width {
            get {
                return ((int)(this["Window_Width"]));
            }
            set {
                this["Window_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("750")]
        public int Window_Height {
            get {
                return ((int)(this["Window_Height"]));
            }
            set {
                this["Window_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string osu_path {
            get {
                return ((string)(this["osu_path"]));
            }
            set {
                this["osu_path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Backup_Enabled {
            get {
                return ((bool)(this["Backup_Enabled"]));
            }
            set {
                this["Backup_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Backup_Folder {
            get {
                return ((string)(this["Backup_Folder"]));
            }
            set {
                this["Backup_Folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60000")]
        public int Backup_Interval {
            get {
                return ((int)(this["Backup_Interval"]));
            }
            set {
                this["Backup_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int Idle_Interval {
            get {
                return ((int)(this["Idle_Interval"]));
            }
            set {
                this["Idle_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int Drawing_Interval {
            get {
                return ((int)(this["Drawing_Interval"]));
            }
            set {
                this["Drawing_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Combo_Colour {
            get {
                return ((bool)(this["Combo_Colour"]));
            }
            set {
                this["Combo_Colour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Show_Console {
            get {
                return ((bool)(this["Show_Console"]));
            }
            set {
                this["Show_Console"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Log_Program {
            get {
                return ((bool)(this["Log_Program"]));
            }
            set {
                this["Log_Program"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Log_EditorReader {
            get {
                return ((bool)(this["Log_EditorReader"]));
            }
            set {
                this["Log_EditorReader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Log_BeatmapConverter {
            get {
                return ((bool)(this["Log_BeatmapConverter"]));
            }
            set {
                this["Log_BeatmapConverter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Log_Drawing {
            get {
                return ((bool)(this["Log_Drawing"]));
            }
            set {
                this["Log_Drawing"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Log_Backup {
            get {
                return ((bool)(this["Log_Backup"]));
            }
            set {
                this["Log_Backup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Log_Timer {
            get {
                return ((bool)(this["Log_Timer"]));
            }
            set {
                this["Log_Timer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Log_Level {
            get {
                return ((int)(this["Log_Level"]));
            }
            set {
                this["Log_Level"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Log_BeatmapBuilder {
            get {
                return ((bool)(this["Log_BeatmapBuilder"]));
            }
            set {
                this["Log_BeatmapBuilder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimingLine_ShowRed {
            get {
                return ((bool)(this["TimingLine_ShowRed"]));
            }
            set {
                this["TimingLine_ShowRed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TimingLine_ShowGreen {
            get {
                return ((bool)(this["TimingLine_ShowGreen"]));
            }
            set {
                this["TimingLine_ShowGreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BarLine_Show {
            get {
                return ((bool)(this["BarLine_Show"]));
            }
            set {
                this["BarLine_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int ScreensContain {
            get {
                return ((int)(this["ScreensContain"]));
            }
            set {
                this["ScreensContain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Selected_Show {
            get {
                return ((bool)(this["Selected_Show"]));
            }
            set {
                this["Selected_Show"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Language_String {
            get {
                return ((string)(this["Language_String"]));
            }
            set {
                this["Language_String"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FilterNearbyHitObjects {
            get {
                return ((bool)(this["FilterNearbyHitObjects"]));
            }
            set {
                this["FilterNearbyHitObjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int WorkCancelAfter {
            get {
                return ((int)(this["WorkCancelAfter"]));
            }
            set {
                this["WorkCancelAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Window_X {
            get {
                return ((int)(this["Window_X"]));
            }
            set {
                this["Window_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Window_Y {
            get {
                return ((int)(this["Window_Y"]));
            }
            set {
                this["Window_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Window_Maximized {
            get {
                return ((bool)(this["Window_Maximized"]));
            }
            set {
                this["Window_Maximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LightBlue")]
        public global::System.Drawing.Color Color_HitObject_Label {
            get {
                return ((global::System.Drawing.Color)(this["Color_HitObject_Label"]));
            }
            set {
                this["Color_HitObject_Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Auto_Topmost {
            get {
                return ((bool)(this["Auto_Topmost"]));
            }
            set {
                this["Auto_Topmost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Bookmark_FolderPath {
            get {
                return ((string)(this["Bookmark_FolderPath"]));
            }
            set {
                this["Bookmark_FolderPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Bookmark_AutoLoadSave {
            get {
                return ((bool)(this["Bookmark_AutoLoadSave"]));
            }
            set {
                this["Bookmark_AutoLoadSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Bookmark_AutoLoadWithStyle {
            get {
                return ((bool)(this["Bookmark_AutoLoadWithStyle"]));
            }
            set {
                this["Bookmark_AutoLoadWithStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Bookmark_LineStyle_1 {
            get {
                return ((int)(this["Bookmark_LineStyle_1"]));
            }
            set {
                this["Bookmark_LineStyle_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Bookmark_LineStyle_2 {
            get {
                return ((int)(this["Bookmark_LineStyle_2"]));
            }
            set {
                this["Bookmark_LineStyle_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Bookmark_LineStyle_3 {
            get {
                return ((int)(this["Bookmark_LineStyle_3"]));
            }
            set {
                this["Bookmark_LineStyle_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Bookmark_LineStyle_4 {
            get {
                return ((int)(this["Bookmark_LineStyle_4"]));
            }
            set {
                this["Bookmark_LineStyle_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Bookmark_LineStyle_5 {
            get {
                return ((int)(this["Bookmark_LineStyle_5"]));
            }
            set {
                this["Bookmark_LineStyle_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Bookmark_LineStyle_6 {
            get {
                return ((int)(this["Bookmark_LineStyle_6"]));
            }
            set {
                this["Bookmark_LineStyle_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Bookmark_LineStyle_7 {
            get {
                return ((int)(this["Bookmark_LineStyle_7"]));
            }
            set {
                this["Bookmark_LineStyle_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Bookmark_LineStyle_8 {
            get {
                return ((int)(this["Bookmark_LineStyle_8"]));
            }
            set {
                this["Bookmark_LineStyle_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Bookmark_Width_1 {
            get {
                return ((int)(this["Bookmark_Width_1"]));
            }
            set {
                this["Bookmark_Width_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int Bookmark_Width_2 {
            get {
                return ((int)(this["Bookmark_Width_2"]));
            }
            set {
                this["Bookmark_Width_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Bookmark_Width_3 {
            get {
                return ((int)(this["Bookmark_Width_3"]));
            }
            set {
                this["Bookmark_Width_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Bookmark_Width_4 {
            get {
                return ((int)(this["Bookmark_Width_4"]));
            }
            set {
                this["Bookmark_Width_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Bookmark_Width_5 {
            get {
                return ((int)(this["Bookmark_Width_5"]));
            }
            set {
                this["Bookmark_Width_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Bookmark_Width_6 {
            get {
                return ((int)(this["Bookmark_Width_6"]));
            }
            set {
                this["Bookmark_Width_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Bookmark_Width_7 {
            get {
                return ((int)(this["Bookmark_Width_7"]));
            }
            set {
                this["Bookmark_Width_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Bookmark_Width_8 {
            get {
                return ((int)(this["Bookmark_Width_8"]));
            }
            set {
                this["Bookmark_Width_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color Bookmark_Color_1 {
            get {
                return ((global::System.Drawing.Color)(this["Bookmark_Color_1"]));
            }
            set {
                this["Bookmark_Color_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pink")]
        public global::System.Drawing.Color Bookmark_Color_2 {
            get {
                return ((global::System.Drawing.Color)(this["Bookmark_Color_2"]));
            }
            set {
                this["Bookmark_Color_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Yellow")]
        public global::System.Drawing.Color Bookmark_Color_3 {
            get {
                return ((global::System.Drawing.Color)(this["Bookmark_Color_3"]));
            }
            set {
                this["Bookmark_Color_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color Bookmark_Color_4 {
            get {
                return ((global::System.Drawing.Color)(this["Bookmark_Color_4"]));
            }
            set {
                this["Bookmark_Color_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color Bookmark_Color_5 {
            get {
                return ((global::System.Drawing.Color)(this["Bookmark_Color_5"]));
            }
            set {
                this["Bookmark_Color_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public global::System.Drawing.Color Bookmark_Color_6 {
            get {
                return ((global::System.Drawing.Color)(this["Bookmark_Color_6"]));
            }
            set {
                this["Bookmark_Color_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aqua")]
        public global::System.Drawing.Color Bookmark_Color_7 {
            get {
                return ((global::System.Drawing.Color)(this["Bookmark_Color_7"]));
            }
            set {
                this["Bookmark_Color_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Purple")]
        public global::System.Drawing.Color Bookmark_Color_8 {
            get {
                return ((global::System.Drawing.Color)(this["Bookmark_Color_8"]));
            }
            set {
                this["Bookmark_Color_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HyperDash")]
        public string Bookmark_Comment_1 {
            get {
                return ((string)(this["Bookmark_Comment_1"]));
            }
            set {
                this["Bookmark_Comment_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dash")]
        public string Bookmark_Comment_2 {
            get {
                return ((string)(this["Bookmark_Comment_2"]));
            }
            set {
                this["Bookmark_Comment_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AntiFlow")]
        public string Bookmark_Comment_3 {
            get {
                return ((string)(this["Bookmark_Comment_3"]));
            }
            set {
                this["Bookmark_Comment_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Move")]
        public string Bookmark_Comment_4 {
            get {
                return ((string)(this["Bookmark_Comment_4"]));
            }
            set {
                this["Bookmark_Comment_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Type 5")]
        public string Bookmark_Comment_5 {
            get {
                return ((string)(this["Bookmark_Comment_5"]));
            }
            set {
                this["Bookmark_Comment_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Type 6")]
        public string Bookmark_Comment_6 {
            get {
                return ((string)(this["Bookmark_Comment_6"]));
            }
            set {
                this["Bookmark_Comment_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Type 7")]
        public string Bookmark_Comment_7 {
            get {
                return ((string)(this["Bookmark_Comment_7"]));
            }
            set {
                this["Bookmark_Comment_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Type 8")]
        public string Bookmark_Comment_8 {
            get {
                return ((string)(this["Bookmark_Comment_8"]));
            }
            set {
                this["Bookmark_Comment_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Log_Bookmark {
            get {
                return ((bool)(this["Log_Bookmark"]));
            }
            set {
                this["Log_Bookmark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Bookmark_RegisterHotKey {
            get {
                return ((bool)(this["Bookmark_RegisterHotKey"]));
            }
            set {
                this["Bookmark_RegisterHotKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Show_CubicFittingCurve {
            get {
                return ((bool)(this["Show_CubicFittingCurve"]));
            }
            set {
                this["Show_CubicFittingCurve"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Use_Stable_Converter {
            get {
                return ((bool)(this["Use_Stable_Converter"]));
            }
            set {
                this["Use_Stable_Converter"] = value;
            }
        }
    }
}
